// Generated by generate_keycodes.sh from keycodes.json.
// Do not edit by hand -- edit the JSON and re-run the script.

/// The parsed vocabulary of one `key:` token, matching KeyCode in
/// ~/esp/SMK/Sources/SMKCore/KeyCodesGenerated.swift entry for entry.
enum KeyName: String, CaseIterable, Hashable {
    case a = "a"
    case b = "b"
    case c = "c"
    case d = "d"
    case e = "e"
    case f = "f"
    case g = "g"
    case h = "h"
    case i = "i"
    case j = "j"
    case k = "k"
    case l = "l"
    case m = "m"
    case n = "n"
    case o = "o"
    case p = "p"
    case q = "q"
    case r = "r"
    case s = "s"
    case t = "t"
    case u = "u"
    case v = "v"
    case w = "w"
    case x = "x"
    case y = "y"
    case z = "z"
    case k1 = "1"
    case k2 = "2"
    case k3 = "3"
    case k4 = "4"
    case k5 = "5"
    case k6 = "6"
    case k7 = "7"
    case k8 = "8"
    case k9 = "9"
    case k0 = "0"
    case enter = "enter"
    case escape = "escape"
    case backspace = "backspace"
    case tab = "tab"
    case space = "space"
    case minus = "minus"
    case equal = "equal"
    case leftBracket = "leftBracket"
    case rightBracket = "rightBracket"
    case backslash = "backslash"
    case semicolon = "semicolon"
    case quote = "quote"
    case grave = "grave"
    case comma = "comma"
    case period = "period"
    case slash = "slash"
    case capsLock = "capsLock"
    case f1 = "f1"
    case f2 = "f2"
    case f3 = "f3"
    case f4 = "f4"
    case f5 = "f5"
    case f6 = "f6"
    case f7 = "f7"
    case f8 = "f8"
    case f9 = "f9"
    case f10 = "f10"
    case f11 = "f11"
    case f12 = "f12"
    case printScreen = "printScreen"
    case scrollLock = "scrollLock"
    case pause = "pause"
    case home = "home"
    case pageUp = "pageUp"
    case delete = "delete"
    case end = "end"
    case pageDown = "pageDown"
    case leftArrow = "left"
    case rightArrow = "right"
    case upArrow = "up"
    case downArrow = "down"
    case application = "application"
}

extension KeyName {
    var displayLabel: String {
        switch self {
        case .a: return "A"
        case .b: return "B"
        case .c: return "C"
        case .d: return "D"
        case .e: return "E"
        case .f: return "F"
        case .g: return "G"
        case .h: return "H"
        case .i: return "I"
        case .j: return "J"
        case .k: return "K"
        case .l: return "L"
        case .m: return "M"
        case .n: return "N"
        case .o: return "O"
        case .p: return "P"
        case .q: return "Q"
        case .r: return "R"
        case .s: return "S"
        case .t: return "T"
        case .u: return "U"
        case .v: return "V"
        case .w: return "W"
        case .x: return "X"
        case .y: return "Y"
        case .z: return "Z"
        case .k1: return "1"
        case .k2: return "2"
        case .k3: return "3"
        case .k4: return "4"
        case .k5: return "5"
        case .k6: return "6"
        case .k7: return "7"
        case .k8: return "8"
        case .k9: return "9"
        case .k0: return "0"
        case .enter: return "⏎"
        case .escape: return "Esc"
        case .backspace: return "⌫"
        case .tab: return "⇥"
        case .space: return "␣"
        case .minus: return "-"
        case .equal: return "="
        case .leftBracket: return "["
        case .rightBracket: return "]"
        case .backslash: return "\\"
        case .semicolon: return ";"
        case .quote: return "'"
        case .grave: return "`"
        case .comma: return ","
        case .period: return "."
        case .slash: return "/"
        case .capsLock: return "Caps"
        case .f1: return "F1"
        case .f2: return "F2"
        case .f3: return "F3"
        case .f4: return "F4"
        case .f5: return "F5"
        case .f6: return "F6"
        case .f7: return "F7"
        case .f8: return "F8"
        case .f9: return "F9"
        case .f10: return "F10"
        case .f11: return "F11"
        case .f12: return "F12"
        case .printScreen: return "PrtSc"
        case .scrollLock: return "ScrLk"
        case .pause: return "Pause"
        case .home: return "Home"
        case .pageUp: return "PgUp"
        case .delete: return "⌦"
        case .end: return "End"
        case .pageDown: return "PgDn"
        case .leftArrow: return "←"
        case .rightArrow: return "→"
        case .upArrow: return "↑"
        case .downArrow: return "↓"
        case .application: return "Menu"
        }
    }

    /// The HID usage this token resolves to in the firmware. The editor never
    /// puts this on the wire -- it sends token strings -- but carrying it lets
    /// the cross-repo agreement test compare actual keycodes rather than only
    /// checking that the same names exist on both sides.
    var hidUsage: UInt8 {
        switch self {
        case .a: return 0x04
        case .b: return 0x05
        case .c: return 0x06
        case .d: return 0x07
        case .e: return 0x08
        case .f: return 0x09
        case .g: return 0x0A
        case .h: return 0x0B
        case .i: return 0x0C
        case .j: return 0x0D
        case .k: return 0x0E
        case .l: return 0x0F
        case .m: return 0x10
        case .n: return 0x11
        case .o: return 0x12
        case .p: return 0x13
        case .q: return 0x14
        case .r: return 0x15
        case .s: return 0x16
        case .t: return 0x17
        case .u: return 0x18
        case .v: return 0x19
        case .w: return 0x1A
        case .x: return 0x1B
        case .y: return 0x1C
        case .z: return 0x1D
        case .k1: return 0x1E
        case .k2: return 0x1F
        case .k3: return 0x20
        case .k4: return 0x21
        case .k5: return 0x22
        case .k6: return 0x23
        case .k7: return 0x24
        case .k8: return 0x25
        case .k9: return 0x26
        case .k0: return 0x27
        case .enter: return 0x28
        case .escape: return 0x29
        case .backspace: return 0x2A
        case .tab: return 0x2B
        case .space: return 0x2C
        case .minus: return 0x2D
        case .equal: return 0x2E
        case .leftBracket: return 0x2F
        case .rightBracket: return 0x30
        case .backslash: return 0x31
        case .semicolon: return 0x33
        case .quote: return 0x34
        case .grave: return 0x35
        case .comma: return 0x36
        case .period: return 0x37
        case .slash: return 0x38
        case .capsLock: return 0x39
        case .f1: return 0x3A
        case .f2: return 0x3B
        case .f3: return 0x3C
        case .f4: return 0x3D
        case .f5: return 0x3E
        case .f6: return 0x3F
        case .f7: return 0x40
        case .f8: return 0x41
        case .f9: return 0x42
        case .f10: return 0x43
        case .f11: return 0x44
        case .f12: return 0x45
        case .printScreen: return 0x46
        case .scrollLock: return 0x47
        case .pause: return 0x48
        case .home: return 0x4A
        case .pageUp: return 0x4B
        case .delete: return 0x4C
        case .end: return 0x4D
        case .pageDown: return 0x4E
        case .leftArrow: return 0x50
        case .rightArrow: return 0x4F
        case .upArrow: return 0x52
        case .downArrow: return 0x51
        case .application: return 0x65
        }
    }
}

extension KeyName {
    static let letters: [KeyName] = [.a, .b, .c, .d, .e, .f, .g, .h, .i, .j, .k, .l, .m, .n, .o, .p, .q, .r, .s, .t, .u, .v, .w, .x, .y, .z]
    static let digits: [KeyName] = [.k1, .k2, .k3, .k4, .k5, .k6, .k7, .k8, .k9, .k0]
    static let editing: [KeyName] = [.enter, .escape, .backspace, .tab, .space, .minus, .equal, .leftBracket, .rightBracket, .backslash, .semicolon, .quote, .grave, .comma, .period, .slash, .capsLock, .delete]
    static let functionKeys: [KeyName] = [.f1, .f2, .f3, .f4, .f5, .f6, .f7, .f8, .f9, .f10, .f11, .f12]
    static let navigation: [KeyName] = [.home, .pageUp, .end, .pageDown, .leftArrow, .rightArrow, .upArrow, .downArrow]
    static let keypad: [KeyName] = []
    static let editingCommands: [KeyName] = []
    static let system: [KeyName] = [.printScreen, .scrollLock, .pause, .application]
    static let international: [KeyName] = []
    static let legacy: [KeyName] = []

    /// Palette sections in display order, consumed by PaletteDrawerView for
    /// both rendering and its height math. Groups with no members are dropped
    /// so an empty section never reserves drawer height.
    static var allGroups: [(title: String, keys: [KeyName], rows: Int)] {
        [
            (title: "Letters", keys: letters, rows: 2),
            (title: "Numbers", keys: digits, rows: 1),
            (title: "Editing & Punctuation", keys: editing, rows: 1),
            (title: "Function Keys", keys: functionKeys, rows: 1),
            (title: "Navigation", keys: navigation, rows: 1),
            (title: "Keypad", keys: keypad, rows: 1),
            (title: "Editing Commands", keys: editingCommands, rows: 1),
            (title: "System", keys: system, rows: 1),
            (title: "International", keys: international, rows: 1),
            (title: "Legacy", keys: legacy, rows: 1),
        ].filter { !$0.keys.isEmpty }
    }
}
