import Foundation
import SwiftCrossUI
import Testing
@testable import SMKConfigurator

/// Guards the Task1<->Task2 filename contract: every `AppIcon` case must
/// have a real bundled PNG for both color schemes on this (macOS) test
/// host, generated by `Scripts/generate-icons.sh` under
/// `Resources/macOS/Icons/<light|dark>/<icon>.png`. If an icon is added to
/// `AppIcon` without a matching generated asset, this test catches it
/// instead of the app silently rendering a blank icon slot at runtime.
@Suite("IconLoader resolves a bundled PNG for every AppIcon case and color scheme")
struct IconLoaderTests {
    @Test(
        "every AppIcon case resolves for both light and dark",
        arguments: AppIcon.allCases, [ColorScheme.light, ColorScheme.dark]
    )
    func resolvesBundledIcon(icon: AppIcon, colorScheme: ColorScheme) {
        let url = IconLoader.url(for: icon, colorScheme: colorScheme)
        #expect(url != nil, "no bundled PNG for \(icon.rawValue) (\(colorScheme))")
    }

    /// Doesn't touch `Bundle.module`, so unlike `resolvesBundledIcon` this
    /// actually exercises on every platform, including the Windows/Linux CI
    /// this project can't run `swift test` on locally -- guards the
    /// nil-icon fallback (`RailButton`/`ToolbarIconButton`) actually has
    /// legible text for every case, not just the ones this test host
    /// happens to bundle a PNG for.
    @Test("every AppIcon case has a non-empty fallbackLabel", arguments: AppIcon.allCases)
    func fallbackLabelIsNonEmpty(icon: AppIcon) {
        #expect(!icon.fallbackLabel.isEmpty, "\(icon.rawValue) has no fallbackLabel")
    }
}
